"""Generic source-fuzzing scan tool."""

from typing import Any, Dict, Optional

from api.tools.common import run_scan


def run_fuzzing_scan(
    tool: str,
    workspace_id: str,
    scan_path: Optional[str] = None,
    config: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Run a white-box, coverage-guided source-fuzzing campaign with the specified
    engine against a per-target harness in the workspace source tree.

    Source fuzzing is used early in the methodology — after SAST flags a suspect
    function and before any live testing — to confirm a triggering input directly
    in the code. You write a small harness that feeds fuzzer-generated bytes into
    the suspect function; the engine then searches for an input that crashes it.

    Args:
        tool: Fuzzing engine to run. One of:
            - ``atheris``    — Python (libFuzzer-based)
            - ``jazzer``     — JVM / Java & Kotlin (libFuzzer-based)
            - ``jazzerjs``   — JavaScript / Node.js (alias: ``jazzer.js``)
            - ``php-fuzzer`` — PHP
        workspace_id: UUID of the workspace whose source the harness lives in.
        scan_path: Optional relative path within the workspace; the ``harness``
            (and ``corpus`` / ``classpath``) paths in ``config`` are resolved
            relative to ``workspace/scan_path``.
        config: Engine configuration. Common keys:
            - ``harness`` (required for atheris/jazzerjs/php-fuzzer): relative path
              to the harness file
              (Python ``atheris.Fuzz`` script / JS module exporting ``fuzz`` /
              PHP file calling ``$fuzzer->setTarget(...)``).
            - ``target_class`` (required for jazzer): fully-qualified fuzz target
              class exposing ``fuzzerTestOneInput``.
            - ``classpath`` (jazzer): relative path(s) to compiled classes / jars
              (colon-separated or a list).
            - ``max_total_time`` (int seconds, default 60): fuzzing time budget.
            - ``runs`` (int): cap on the number of fuzzing iterations.
            - ``corpus`` (str): relative path to a seed-corpus directory.
            - ``engine_args`` (list[str]): extra libFuzzer flags passed verbatim.

    Returns:
        Scan result. Fuzzing campaigns usually exceed the MCP timeout and report
        ``status: backgrounded``; retrieve the crash report later with
        ``get_fuzzing_report``. Each crash artifact becomes one finding (with the
        crashing input, base64-encoded, and the stack trace).
    """
    return run_scan("fuzzing", tool, workspace_id, scan_path, config)
